openapi: 3.0.0
info:
  title: Destiny Vault Assistant API
  version: 1.0.0
paths:
  /vault:
    post:
      summary: Get Destiny 2 vault inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
      responses:
        '200':
          description: Vault inventory returned

  /vault/decoded:
    post:
      summary: Decode Destiny 2 vault inventory
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
      responses:
        '200':
          description: Decoded vault inventory

  /characters:
    post:
      summary: Get Destiny 2 character equipment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
      responses:
        '200':
          description: Character equipment returned

  /characters/decoded:
    post:
      summary: Decode Destiny 2 character equipment
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
      responses:
        '200':
          description: Decoded character equipment

  /dim/backup:
    post:
      summary: Save a DIM backup
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                membership_id:
                  type: string
                dim_backup:
                  type: string
      responses:
        '200':
          description: DIM backup saved

  /dim/list:
    get:
      summary: List all DIM backups
      responses:
        '200':
          description: DIM backups listed

  /session:
    get:
      summary: Get current session info
      responses:
        '200':
          description: Session info returned

  /session/token:
    get:
      summary: Get access token and membership ID
      responses:
        '200':
          description: Token returned

  /assistant/init:
    post:
      summary: Initialize assistant session with access token
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
      responses:
        '200':
          description: Assistant initialized

  /manifest/item:
    get:
      summary: Look up Destiny 2 manifest item definition
      parameters:
        - in: query
          name: definition
          required: true
          schema:
            type: string
        - in: query
          name: hash
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Manifest item definition returned

  /token/refresh:
    get:
      summary: Refresh the Bungie access token
      responses:
        '200':
          description: Access token refreshed