name: Deploy Static Website to Azure Storage

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python (for Azure CLI)
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Log in to Azure
        uses: azure/login@v2
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: Upload static website files to $web container
        run: |
          az storage blob upload-batch \
            --account-name stcoreprod59o7 \
            --destination '$web/the-rob-vault' \
            --source ./static \
            --auth-mode login
